name: deploy-model-training-pipeline

on:
  workflow_dispatch:

jobs:
  set-env-branch:
    runs-on: ubuntu-latest
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prod-branch
        name: set-prod-branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "CONFIG_FILE=config-infra-prod.yml" >> $GITHUB_ENV
      - id: set-dev-branch
        name: set-dev-branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "CONFIG_FILE=config-infra-dev.yml" >> $GITHUB_ENV
      - id: set-output-defaults
        name: set-output-defaults
        run: echo "config-file=$CONFIG_FILE" >> $GITHUB_OUTPUT

  get-config:
    needs: set-env-branch
    uses: 0Upjh80d/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: ${{ needs.set-env-branch.outputs.config-file }}

  register-environment:
    needs: get-config
    uses: 0Upjh80d/mlops-templates/.github/workflows/register-environment.yml@main
    with:
      environment_file: mlops/azureml/train/train-env.yml
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      conda_file: data-science/environment/train-conda.yml
    secrets:
      creds: ${{ github.ref == 'refs/heads/main' && secrets.AZURE_CREDENTIALS_PROD || secrets.AZURE_CREDENTIALS_DEV }}

  register-dataset:
    needs: get-config
    uses: 0Upjh80d/mlops-templates/.github/workflows/register-dataset.yml@main
    with:
      data_file: mlops/azureml/train/data.yml
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
    secrets:
      creds: ${{ github.ref == 'refs/heads/main' && secrets.AZURE_CREDENTIALS_PROD || secrets.AZURE_CREDENTIALS_DEV }}

  create-compute:
    needs: get-config
    uses: 0Upjh80d/mlops-templates/.github/workflows/create-compute.yml@main
    with:
      cluster_name: cpu-cluster
      size: Standard_DS3_v2
      min_instances: 0
      max_instances: 4
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      cluster_tier: dedicated # [low_priority, dedicated]
    secrets:
      creds: ${{ github.ref == 'refs/heads/main' && secrets.AZURE_CREDENTIALS_PROD || secrets.AZURE_CREDENTIALS_DEV }}

  run-model-training-pipeline:
    needs: [get-config, register-environment, register-dataset, create-compute]
    uses: 0Upjh80d/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      parameters_file: mlops/azureml/train/pipeline.yml
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      job_name: test
    secrets:
      creds: ${{ github.ref == 'refs/heads/main' && secrets.AZURE_CREDENTIALS_PROD || secrets.AZURE_CREDENTIALS_DEV }}
